name: Release
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: vuetifyjs/setup-action@master
      - run: pnpm run build
        env:
          VITE_API_SERVER_URL: ${{ vars.API_SERVER_URL }}
      - uses: vuetifyjs/coolify-action@master
        with:
          imageName: tryvuetify
          token: ${{ secrets.GITHUB_TOKEN  }}
          coolifyWebhook: ${{ secrets.COOLIFY_WEBHOOK }}
          coolifySecret: ${{ secrets.COOLIFY_TOKEN }}
